# Generated by Django 3.2.10 on 2022-03-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoTurma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aluno_turma',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateField(verbose_name='Data de início da aula')),
                ('data_fim', models.DateField(verbose_name='Data de término da aula')),
                ('horario_inicio', models.TimeField(verbose_name='Horario de início da aula')),
                ('horario_fim', models.TimeField(verbose_name='Horario de término da aula')),
                ('horario_ativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'aula',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('status_turma', models.BooleanField(default=True)),
                ('vagas_turma', models.IntegerField(default=40)),
            ],
            options={
                'db_table': 'turma',
            },
        ),
        migrations.CreateModel(
            name='TurmaAula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aula')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
            options={
                'db_table': 'aula_turma',
            },
        ),
    ]
